Repository magento/magento-coding-standard, pull requests merged in 2019-08, with the labels that each got.

#120 MC-18816: Impelement an better check for ThrowCatchSniff
  Magento2/Sniffs/Exceptions/ThrowCatchSniff.php
  Magento2/Tests/Exceptions/ThrowCatchUnitTest.1.inc
  Magento2/Tests/Exceptions/ThrowCatchUnitTest.2.inc
  Magento2/Tests/Exceptions/ThrowCatchUnitTest.php
Labels: Partner: TechDivision, Progress: review, partners-contribution

#126 #95 : Empty FUNCTION statement detected should be allowed for around plugins
  Magento2/Sniffs/CodeAnalysis/EmptyBlockSniff.php
  Magento2/Tests/CodeAnalysis/EmptyBlockUnitTest.inc
Labels: Progress: changes requested

#123 #102 Add alternative for php pathinfo function is discouraged
  Magento2/Sniffs/Functions/DiscouragedFunctionSniff.php
Labels: Partner: Space 48, Progress: review, partners-contribution

#130 Prevent none zero exit code
  README.md
Labels: Progress: review

#122 #121 Magento2.Templates.HelperInTemplate Rule porposal
  Magento2/Sniffs/Templates/ThisInTemplateSniff.md
  Magento2/Sniffs/Templates/ThisInTemplateSniff.php
Labels: Partner: Space 48, Progress: review, partners-contribution

#127 Fixed issue in line length sniff for phrase and __ keyword
  Magento2/Sniffs/Files/LineLengthSniff.php
  Magento2/Sniffs/PHP/FinalImplementationSniff.php
  Magento2/Sniffs/Security/LanguageConstructSniff.php
  Magento2/Sniffs/Strings/ExecutableRegExSniff.php
  Magento2/Tests/Files/LineLengthUnitTest.inc
  Magento2/Tests/Files/LineLengthUnitTest.php
  Magento2/ruleset.xml
  README.md
Labels: Progress: review

#77 #21: Impelement rule
  Magento2/Sniffs/Exceptions/TryProcessSystemResourcesSniff.php
  Magento2/Tests/Exceptions/TryProcessSystemResourcesUnitTest.inc
  Magento2/Tests/Exceptions/TryProcessSystemResourcesUnitTest.php
  Magento2/ruleset.xml
Labels: Partner: TechDivision, Progress: approved, accepted, partners-contribution

#132 No longer require a space before a colon for control structures using…
  Magento2/ruleset.xml
Labels: Progress: approved
