Repository magento/magento-coding-standard, pull requests merged in 2019-10, with the labels that each got.

#150 How to use phpcbf
  README.md
Labels: Progress: review

#151 Git ignore for IDE files
  .gitignore
Labels: Progress: approved

#153 Fix typo in DiscouragedFunctionSniff
  Magento2/Sniffs/Functions/DiscouragedFunctionSniff.php
Labels: Community Insider: Magecom, Progress: approved, community-insider-contribution
