Repository magento/magento-coding-standard, pull requests merged in 2019-04, with the labels that each got.

#59 Proxies and interceptors
  Magento2/Sniffs/Classes/DiscouragedDependenciesSniff.php
  Magento2/Tests/Classes/DiscouragedDependenciesUnitTest.1.inc
  Magento2/Tests/Classes/DiscouragedDependenciesUnitTest.2.inc
  Magento2/Tests/Classes/DiscouragedDependenciesUnitTest.php
  Magento2/ruleset.xml
Labels: event: MageTestFest2019, partners-contribution, waiting for feedback

#72 #20 Impelement ArrayMerge sniff in foreach
  Magento2/Sniffs/Performance/ForeachArrayMergeSniff.php
  Magento2/Tests/Performance/ForeachArrayMergeUnitTest.inc
  Magento2/Tests/Performance/ForeachArrayMergeUnitTest.php
  Magento2/ruleset.xml
Labels: Partner: TechDivision, partners-contribution

#85 upgrade php codesniffer up to version 3.4
  composer.json
  composer.lock
Labels: Community Insider: Magecom, community-insider-contribution
