Repository magento/magento-coding-standard, pull requests merged in 2020-08, with the labels that each got.

#186 Suggest \Magento\Framework\Shell::execute as alternative to exec
  Magento2/Sniffs/Security/InsecureFunctionSniff.php
Labels: Partner: integer_net GmbH, Progress: approved, partners-contribution

#190 Run tests on php 7.4
  .travis.yml
Labels: Progress: approved

#189 Added sniff for deprecated model methods. #187
  Magento2/Sniffs/Methods/DeprecatedModelMethodSniff.php
  Magento2/Tests/Methods/DeprecatedModelMethodUnitTest.inc
  Magento2/Tests/Methods/DeprecatedModelMethodUnitTest.php
  Magento2/ruleset.xml
Labels: Community Insider: Cedcommerce, Progress: review, community-insider-contribution

#192 PHP 7.4 compatibility
  composer.json
  composer.lock
Labels: Progress: approved
