Repository magento/magento-coding-standard, pull requests merged in 2021-09, with the labels that each got.

#237 AC-942: Create unit test for Magento2\Less\ColonSpacingSniff check
  Magento2/Sniffs/Less/ColonSpacingSniff.php
  Magento2/Tests/Less/ColonSpacingUnitTest.less
  Magento2/Tests/Less/ColonSpacingUnitTest.php
Labels: Progress: approved

#247 AC-953: Create unit test for Magento2\Less\TypeSelectorConcatenationSniff check
  Magento2/Tests/Less/TypeSelectorConcatenationUnitTest.less
  Magento2/Tests/Less/TypeSelectorConcatenationUnitTest.php
Labels: Progress: approved

#252 AC-955: Create unit test for Magento2\Less\VariablesSniff check
  Magento2/Tests/Less/VariablesUnitTest.less
  Magento2/Tests/Less/VariablesUnitTest.php
Labels: Progress: approved

#244 AC-948: Create unit test for Magento2\Less\PropertiesLineBreakSniff
  Magento2/Tests/Less/PropertiesLineBreakUnitTest.less
  Magento2/Tests/Less/PropertiesLineBreakUnitTest.php
Labels: Progress: approved

#251 AC-956: Create unit test for Magento2\Less\ZeroUnitsSniff check
  Magento2/Sniffs/Less/ZeroUnitsSniff.php
  Magento2/Tests/Less/ZeroUnitsUnitTest.less
  Magento2/Tests/Less/ZeroUnitsUnitTest.php
Labels: Progress: approved

#248 AC-950: Create unit test for Magento2\Less\QuotesSniff check
  Magento2/Tests/Less/QuotesUnitTest.less
  Magento2/Tests/Less/QuotesUnitTest.php
Labels: Progress: approved

#250 AC-954: Create unit test for Magento2\Less\TypeSelectorsSniff check
  Magento2/Tests/Less/TypeSelectorsUnitTest.less
  Magento2/Tests/Less/TypeSelectorsUnitTest.php
Labels: Progress: approved

#238 AC-943: Create unit test for Magento2\Less\ColourDefinitionSniff check
  Magento2/Sniffs/Less/ColourDefinitionSniff.php
  Magento2/Tests/Less/ColourDefinitionUnitTest.less
  Magento2/Tests/Less/ColourDefinitionUnitTest.php
Labels: Progress: approved

#230 AC-659 Create phpcs static check for ModuleXMLTest
  Magento2/Sniffs/Legacy/ModuleXMLSniff.php
  Magento2/Tests/Legacy/ModuleXMLUnitTest.1.xml
  Magento2/Tests/Legacy/ModuleXMLUnitTest.2.xml
  Magento2/Tests/Legacy/ModuleXMLUnitTest.3.xml
  Magento2/Tests/Legacy/ModuleXMLUnitTest.php
  Magento2/ruleset.xml
  composer.json
  composer.lock
Labels: Progress: approved

#255 AC-1128: Add severity and type (warning or error) for annotation, htm…
  Magento2/ruleset.xml
Labels: Progress: approved

#254 Ignore PHPUnit results cache file
  .gitignore
Labels: partners-contribution, Progress: approved, Partner: Fisheye

#256 Fix PHP Fatal error when docblock is invalid
  Magento2/Sniffs/Annotation/MethodArgumentsSniff.php
  Magento2/Tests/Annotation/MethodArgumentsUnitTest.inc
  Magento2/Tests/Annotation/MethodArgumentsUnitTest.php
Labels: partners-contribution, Progress: approved, Partner: Fisheye

#258 AC-1100 Catch badly put newlines in LESS files
  Magento2/Sniffs/Less/ColonSpacingSniff.php
  Magento2/Tests/Less/ColonSpacingUnitTest.less
  Magento2/Tests/Less/ColonSpacingUnitTest.php
Labels: Progress: approved

#140 #58 : Implement sniff for class properties PHPDoc formatting
  Magento2/Helpers/Tokenizer/AbstractTokenizer.php
  Magento2/Helpers/Tokenizer/Variable.php
  Magento2/Sniffs/Classes/DiscouragedDependenciesSniff.php
  Magento2/Sniffs/Commenting/ClassPropertyPHPDocFormattingSniff.php
  Magento2/Sniffs/Exceptions/DirectThrowSniff.php
  Magento2/Sniffs/Less/AvoidIdSniff.php
  Magento2/Sniffs/Less/IndentationSniff.php
  Magento2/Sniffs/Less/PropertiesSortingSniff.php
  Magento2/Sniffs/Less/SemicolonSpacingSniff.php
  Magento2/Sniffs/Less/TypeSelectorsSniff.php
  Magento2/Sniffs/Less/ZeroUnitsSniff.php
  Magento2/Sniffs/Methods/DeprecatedModelMethodSniff.php
  Magento2/Sniffs/Security/SuperglobalSniff.php
  Magento2/Sniffs/Security/XssTemplateSniff.php
  Magento2/Tests/Commenting/ClassPropertyPHPDocFormattingUnitTest.inc
  Magento2/Tests/Commenting/ClassPropertyPHPDocFormattingUnitTest.php
  Magento2/ruleset.xml
Labels: needs update, Progress: review

#263 Version 9
  composer.json
  composer.lock
Labels: Progress: ready for review

#261 AC-667: Create phpcs static check for EmailTemplateTest
  Magento2/Sniffs/Legacy/EmailTemplateSniff.php
  Magento2/Tests/Legacy/EmailTemplateUnitTest.1.html
  Magento2/Tests/Legacy/EmailTemplateUnitTest.2.html
  Magento2/Tests/Legacy/EmailTemplateUnitTest.php
  Magento2/ruleset.xml
Labels: Progress: approved

#266 AC-661: Create phpcs static check for XmlTest
  Magento2/Sniffs/Legacy/WidgetXMLSniff.php
  Magento2/Tests/Legacy/WidgetXMLUnitTest.1.xml
  Magento2/Tests/Legacy/WidgetXMLUnitTest.2.xml
  Magento2/Tests/Legacy/WidgetXMLUnitTest.3.xml
  Magento2/Tests/Legacy/WidgetXMLUnitTest.php
  Magento2/ruleset.xml
Labels: Progress: approved

#269 AC-666: Copyright test for another extensions files
  Magento2/Sniffs/Legacy/CopyrightAnotherExtensionsFilesSniff.php
  Magento2/Tests/Legacy/AbstractJsSniffUnitTestCase.php
  Magento2/Tests/Legacy/CopyrightAnotherExtensionsFilesUnitTest.1.xml
  Magento2/Tests/Legacy/CopyrightAnotherExtensionsFilesUnitTest.2.js
  Magento2/Tests/Legacy/CopyrightAnotherExtensionsFilesUnitTest.4.js
  Magento2/Tests/Legacy/CopyrightAnotherExtensionsFilesUnitTest.php
  Magento2/Tests/Legacy/CopyrightAnotherExtensionsFilesUnitTest.xml
  Magento2/ruleset.xml
Labels: Progress: approved

#270 Fixed wrongly returning error for valid descriptions
  Magento2/Sniffs/Commenting/ClassPropertyPHPDocFormattingSniff.php
  Magento2/Tests/Commenting/ClassPropertyPHPDocFormattingUnitTest.inc
  Magento2/Tests/Commenting/ClassPropertyPHPDocFormattingUnitTest.php
Labels: Progress: approved

#271 Increased version to 10
  composer.json
  composer.lock
Labels: Progress: approved

#262 AC-1156: Move custom eslint tests to magento-coding-standard repo
  .github/workflows/php.yml
  .gitignore
  Magento2/Tests/Eslint/AbstractEslintTestCase.php
  Magento2/Tests/Eslint/AndSelfTest.js
  Magento2/Tests/Eslint/AndSelfTest.php
  Magento2/Tests/Eslint/BindUnbindTest.js
  Magento2/Tests/Eslint/BindUnbindTest.php
  Magento2/Tests/Eslint/ClickEventShorthand.js
  Magento2/Tests/Eslint/ClickEventShorthandTest.php
  Magento2/Tests/Eslint/DelegateUndelegateTest.js
  Magento2/Tests/Eslint/DelegateUndelegateTest.php
  Magento2/Tests/Eslint/EventShorthandTest.js
  Magento2/Tests/Eslint/EventShorthandTest.php
  Magento2/Tests/Eslint/SizeTest.js
  Magento2/Tests/Eslint/SizeTest.php
  Magento2/Tests/Eslint/TrimTest.js
  Magento2/Tests/Eslint/TrimTest.php
  README.md
  eslint/.eslintrc
  eslint/.eslintrc-jquery
  eslint/.eslintrc-magento
  eslint/.eslintrc-misc
  eslint/.eslintrc-reset
  eslint/rules/jquery-no-andSelf.js
  eslint/rules/jquery-no-bind-unbind.js
  eslint/rules/jquery-no-click-event-shorthand.js
  eslint/rules/jquery-no-delegate-undelegate.js
  eslint/rules/jquery-no-event-shorthand.js
  eslint/rules/jquery-no-size.js
  eslint/rules/jquery-no-trim.js
  eslint/rules/utils.js
  package-lock.json
  package.json
Labels: Progress: approved

#278 AC-665: Create phpcs static check for ConfigTest
  Magento2/Sniffs/Legacy/ObsoleteConfigNodesSniff.php
  Magento2/Tests/Legacy/ObsoleteConfigNodesUnitTest.1.xml
  Magento2/Tests/Legacy/ObsoleteConfigNodesUnitTest.2.xml
  Magento2/Tests/Legacy/ObsoleteConfigNodesUnitTest.php
  Magento2/ruleset.xml
Labels: Progress: approved

#279 AC-1307: PHP Syntax errors in xml files
  Magento2/ruleset.xml
Labels: Progress: approved

#273 AC-662: Create phpcs static check for AutogeneratedClassNotInConstructorTest
  Magento2/Sniffs/PHP/AutogeneratedClassNotInConstructorSniff.php
  Magento2/Tests/PHP/AutogeneratedClassNotInConstructorUnitTest.1.php.inc
  Magento2/Tests/PHP/AutogeneratedClassNotInConstructorUnitTest.2.php.inc
  Magento2/Tests/PHP/AutogeneratedClassNotInConstructorUnitTest.php
  Magento2/ruleset.xml
Labels: Progress: approved

#281 AC-669 install upgrade test
  Magento2/Sniffs/Legacy/InstallUpgradeSniff.php
  Magento2/Tests/Legacy/InstallUpgradeUnitTest.php
  Magento2/Tests/Legacy/_files/InstallUpgradeUnitTest/InstallData.inc
  Magento2/Tests/Legacy/_files/InstallUpgradeUnitTest/InstallSchema.inc
  Magento2/Tests/Legacy/_files/InstallUpgradeUnitTest/UpgradeData.inc
  Magento2/Tests/Legacy/_files/InstallUpgradeUnitTest/UpgradeSchema.inc
  Magento2/Tests/Legacy/_files/InstallUpgradeUnitTest/data-install-.inc
  Magento2/Tests/Legacy/_files/InstallUpgradeUnitTest/data-upgrade-.inc
  Magento2/Tests/Legacy/_files/InstallUpgradeUnitTest/data/file2.inc
  Magento2/Tests/Legacy/_files/InstallUpgradeUnitTest/install-sample.inc
  Magento2/Tests/Legacy/_files/InstallUpgradeUnitTest/recurring.inc
  Magento2/Tests/Legacy/_files/InstallUpgradeUnitTest/sql/file.inc
  Magento2/Tests/Legacy/_files/InstallUpgradeUnitTest/upgrade-.inc
  Magento2/Tests/Legacy/_files/InstallUpgradeUnitTest/valid-file.inc
  Magento2/ruleset.xml
Labels: Progress: changes requested

#284 AC-1335: Exclude copyright sniff
  Magento2/ruleset.xml
Labels: Progress: approved

#286 Increased version to 11
  composer.json
  composer.lock
Labels: Progress: approved

#289 AC-1339: Detect comment for typed class properties
  Magento2/Sniffs/Commenting/ClassPropertyPHPDocFormattingSniff.php
  Magento2/Tests/Commenting/ClassPropertyPHPDocFormattingUnitTest.inc
Labels: Progress: approved

#290 AC-669: Fixed directory name checking too lax
  Magento2/Sniffs/Legacy/InstallUpgradeSniff.php
  Magento2/Tests/Legacy/_files/InstallUpgradeUnitTest/another-data-folder/file3.inc
  Magento2/Tests/Legacy/_files/InstallUpgradeUnitTest/another-sql-folder/file4.inc
Labels: Progress: approved

#291 Increased version to 12
  composer.json
  composer.lock
Labels: Progress: approved

#292 Version 12 master update
  Magento2/Sniffs/Commenting/ClassPropertyPHPDocFormattingSniff.php
  Magento2/Sniffs/Legacy/InstallUpgradeSniff.php
  Magento2/Tests/Commenting/ClassPropertyPHPDocFormattingUnitTest.inc
  Magento2/Tests/Legacy/_files/InstallUpgradeUnitTest/another-data-folder/file3.inc
  Magento2/Tests/Legacy/_files/InstallUpgradeUnitTest/another-sql-folder/file4.inc
  composer.json
  composer.lock
Labels: Progress: approved

#293 AC-667 Fix ruleset.xml
  Magento2/ruleset.xml
Labels: Progress: approved

#285 AC-674: Create phpcs static check for ObsoleteAclTest
  Magento2/Sniffs/Legacy/ObsoleteAclSniff.php
  Magento2/Tests/Legacy/ObsoleteAclUnitTest.php
  Magento2/Tests/Legacy/ObsoleteAclUnitTest.xml
  Magento2/ruleset.xml
Labels: Progress: approved

#288 AC-677: Create phpcs static test for ObsoleteMenuTest
  Magento2/Sniffs/Legacy/ObsoleteMenuSniff.php
  Magento2/Tests/Legacy/ObsoleteMenuUnitTest.php
  Magento2/Tests/Legacy/ObsoleteMenuUnitTest.xml
  Magento2/ruleset.xml
Labels: Progress: approved

#296 AC-679: Create phpcs static check for ObsoleteSystemConfigurationTest
  Magento2/Sniffs/Legacy/ObsoleteSystemConfigurationSniff.php
  Magento2/Tests/Legacy/ObsoleteSystemConfigurationUnitTest.1.xml
  Magento2/Tests/Legacy/ObsoleteSystemConfigurationUnitTest.2.xml
  Magento2/Tests/Legacy/ObsoleteSystemConfigurationUnitTest.php
  Magento2/ruleset.xml
Labels: Progress: approved
