Repository magento/magento-coding-standard, pull requests merged in 2021-11, with the labels that each got.

#319 Fixed undefined variable error in AutogeneratedClassNotInConstructorSniff
  Magento2/Sniffs/PHP/AutogeneratedClassNotInConstructorSniff.php
  Magento2/Tests/PHP/AutogeneratedClassNotInConstructorUnitTest.1.php.inc
  Magento2/Tests/PHP/AutogeneratedClassNotInConstructorUnitTest.2.php.inc
  Magento2/Tests/PHP/AutogeneratedClassNotInConstructorUnitTest.php
Labels: Progress: approved

#322 Add Sniff for check autovivification on array
  Magento2/Sniffs/PHP/ArrayAutovivificationSniff.php
  Magento2/Tests/PHP/ArrayAutovivificationUnitTest.inc
  Magento2/Tests/PHP/ArrayAutovivificationUnitTest.php
  Magento2/ruleset.xml
Labels: partners-contribution, Progress: approved, Partner: Atwix

#324 Excluded JS files for PSR sniffs
  Magento2/ruleset.xml
Labels: Progress: approved

#320 AC-1509: Remove outdated JSCS static tests from magento
  .github/workflows/php.yml
  eslint/.eslintrc
  eslint/.eslintrc-jscs
  eslint/rules/jquery-no-andSelf.js
  eslint/rules/jquery-no-bind-unbind.js
  eslint/rules/jquery-no-click-event-shorthand.js
  eslint/rules/jquery-no-delegate-undelegate.js
  eslint/rules/jquery-no-event-shorthand.js
  eslint/rules/jquery-no-size.js
  eslint/rules/jquery-no-trim.js
  jscs/.jscsrc
  package-lock.json
  package.json
Labels: Progress: approved

#327 AC-1509: Remove outdated JSCS static tests from magento
  README.md
Labels: Progress: approved

#328 Update rule names for better messaging
  Magento2/Sniffs/Annotation/MethodArgumentsSniff.php
Labels: partners-contribution, Progress: approved, Partner: Fisheye

#325 Created Sniff to validate function without argument
  Magento2/Sniffs/Functions/FunctionsDeprecatedWithoutArgumentSniff.php
  Magento2/Tests/Functions/FunctionsDeprecatedWithoutArgumentUnitTest.inc
  Magento2/Tests/Functions/FunctionsDeprecatedWithoutArgumentUnitTest.php
  Magento2/ruleset.xml
Labels: partners-contribution, Progress: approved, Partner: Atwix

#326 Added deprecated function PHP 8.1 to DiscouragedFunctionSniff
  Magento2/Sniffs/Functions/DiscouragedFunctionSniff.php
  Magento2/Tests/Functions/DiscouragedFunctionUnitTest.inc
  Magento2/Tests/Functions/DiscouragedFunctionUnitTest.php
Labels: partners-contribution, Progress: approved, Partner: Atwix

#330 Added Constant visibility in the ruleset
  Magento2/Sniffs/Classes/DiscouragedDependenciesSniff.php
  Magento2/Sniffs/Html/HtmlDirectiveSniff.php
  Magento2/Sniffs/Less/CommentLevelsSniff.php
  Magento2/Sniffs/Less/TokenizerSymbolsInterface.php
  Magento2/Sniffs/Less/ZeroUnitsSniff.php
  Magento2/Sniffs/Methods/DeprecatedModelMethodSniff.php
  Magento2/ruleset.xml
Labels: Progress: approved

#329 Fixed code array autovivification
  Magento2/Sniffs/PHP/ArrayAutovivificationSniff.php
  Magento2/Tests/PHP/ArrayAutovivificationUnitTest.inc
Labels: partners-contribution, Progress: approved, Partner: Atwix

#334 Fix unit tests
  Magento2Framework/Tests/Header/CopyrightGraphQLUnitTest.php
Labels: Progress: approved

#335 Fix Comment block is missing Failure when Attribute is present after the docblock
  Magento2/Sniffs/Annotation/MethodArgumentsSniff.php
  Magento2/Tests/Annotation/MethodArgumentsUnitTest.inc
  Magento2/Tests/Annotation/MethodArgumentsUnitTest.php
Labels: partners-contribution, Progress: approved, Partner: Atwix

#336 Fixed AutogeneratedClassNotInConstructorSniff for specific code constructions
  Magento2/Sniffs/PHP/AutogeneratedClassNotInConstructorSniff.php
  Magento2/Tests/PHP/AutogeneratedClassNotInConstructorUnitTest.2.php.inc
Labels: Progress: approved

#333 AC-1740: Add rectorphp as a dependency to magento-coding-standard
  .github/workflows/php.yml
  README.md
  composer.json
  composer.lock
  rector.php
Labels: Progress: approved
