Repository magento/magento-coding-standard, pull requests merged in 2021-08, with the labels that each got.

#211 #210: Fixed HtmlDirectiveSniff.php from causing the Fatal Error for c…
  Magento2/Sniffs/Html/HtmlDirectiveSniff.php
Labels: Progress: approved

#218 AC-601: Create phpcs static check for AbstractBlockTest
  Magento2/Sniffs/Legacy/AbstractBlockSniff.php
  Magento2/Tests/Legacy/AbstractBlockUnitTest.inc
  Magento2/Tests/Legacy/AbstractBlockUnitTest.php
  Magento2/ruleset.xml
Labels: Progress: approved

#215 Fix magento/magento-coding-standard#214 with class not found
  Magento2/Helpers/Tokenizer/AbstractTokenizer.php
  Magento2/Helpers/Tokenizer/Parameter.php
  Magento2/Helpers/Tokenizer/Variable.php
  Magento2/Sniffs/Html/HtmlDirectiveSniff.php
Labels: Progress: approved, tech-partners-contribution, Technology Partner: Amasty

#216 Run tests for all file types
  .github/workflows/php.yml
Labels: Progress: approved

#217 Add test coverage for HtmlBindingSniff
  Magento2/Sniffs/Html/HtmlBindingSniff.php
  Magento2/Tests/Html/HtmlBindingSniffUnitTest.1.inc
  Magento2/Tests/Html/HtmlBindingUnitTest.php
Labels: Progress: approved

#221 Version 7
  composer.json
  composer.lock
Labels: Progress: ready for review

#222 Version 7 master update
  .github/workflows/php.yml
  .travis.yml
  Magento2/Helpers/Tokenizer/AbstractTokenizer.php
  Magento2/Helpers/Tokenizer/Parameter.php
  Magento2/Helpers/Tokenizer/Variable.php
  Magento2/Sniffs/Annotation/AnnotationFormatValidator.php
  Magento2/Sniffs/Annotation/MethodAnnotationStructureSniff.php
  Magento2/Sniffs/Annotation/MethodArgumentsSniff.php
  Magento2/Sniffs/Exceptions/DirectThrowSniff.php
  Magento2/Sniffs/GraphQL/ValidArgumentNameSniff.php
  Magento2/Sniffs/GraphQL/ValidEnumValueSniff.php
  Magento2/Sniffs/Html/HtmlBindingSniff.php
  Magento2/Sniffs/Html/HtmlDirectiveSniff.php
  Magento2/Sniffs/Legacy/AbstractBlockSniff.php
  Magento2/Sniffs/Legacy/MageEntitySniff.php
  Magento2/Sniffs/Less/AvoidIdSniff.php
  Magento2/Sniffs/Less/BracesFormattingSniff.php
  Magento2/Sniffs/Less/ClassNamingSniff.php
  Magento2/Sniffs/Less/ColonSpacingSniff.php
  Magento2/Sniffs/Less/ColourDefinitionSniff.php
  Magento2/Sniffs/Less/CombinatorIndentationSniff.php
  Magento2/Sniffs/Less/CommentLevelsSniff.php
  Magento2/Sniffs/Less/ImportantPropertySniff.php
  Magento2/Sniffs/Less/IndentationSniff.php
  Magento2/Sniffs/Less/PropertiesLineBreakSniff.php
  Magento2/Sniffs/Less/PropertiesSortingSniff.php
  Magento2/Sniffs/Less/QuotesSniff.php
  Magento2/Sniffs/Less/SelectorDelimiterSniff.php
  Magento2/Sniffs/Less/SemicolonSpacingSniff.php
  Magento2/Sniffs/Less/TokenizerSymbolsInterface.php
  Magento2/Sniffs/Less/TypeSelectorConcatenationSniff.php
  Magento2/Sniffs/Less/TypeSelectorsSniff.php
  Magento2/Sniffs/Less/VariablesSniff.php
  Magento2/Sniffs/Less/ZeroUnitsSniff.php
  Magento2/Sniffs/Security/XssTemplateSniff.php
  Magento2/Tests/GraphQL/AbstractGraphQLSniffUnitTestCase.php
  Magento2/Tests/Html/HtmlBindingSniffUnitTest.1.inc
  Magento2/Tests/Html/HtmlBindingUnitTest.php
  Magento2/Tests/Legacy/AbstractBlockUnitTest.inc
  Magento2/Tests/Legacy/AbstractBlockUnitTest.php
  Magento2/Tests/Security/XssTemplateUnitTest.inc
  Magento2/ruleset.xml
  PHP_CodeSniffer/Tests/Standards/AbstractSniffUnitTest.php
  composer.json
  composer.lock
Labels: Progress: ready for review

#223 AC-957: Create unit test for Magento2\Html\HtmlDirectiveSniff check
  Magento2/Sniffs/Html/HtmlDirectiveSniff.php
  Magento2/Tests/Html/HtmlBindingUnitTest.1.inc
  Magento2/Tests/Html/HtmlDirectiveUnitTest.1.inc
  Magento2/Tests/Html/HtmlDirectiveUnitTest.2.inc
  Magento2/Tests/Html/HtmlDirectiveUnitTest.php
Labels: Progress: approved

#224 AC-958: create unit test for Magento2\Annotation checks
  Magento2/Sniffs/Annotation/AnnotationFormatValidator.php
  Magento2/Sniffs/Annotation/MethodArgumentsSniff.php
  Magento2/Tests/Annotation/MethodAnnotationStructureUnitTest.inc
  Magento2/Tests/Annotation/MethodAnnotationStructureUnitTest.php
  Magento2/Tests/Annotation/MethodArgumentsUnitTest.inc
  Magento2/Tests/Annotation/MethodArgumentsUnitTest.php
Labels: Progress: approved

#220 Fix ImportsFromTestNamespace from lock on group use with trailing comma
  Magento2/Sniffs/Namespaces/ImportsFromTestNamespaceSniff.php
  Magento2/Tests/Namespaces/ImportsFromTestNamespaceUnitTest.inc
Labels: Progress: approved

#228 Moved abstract unit test to autoload-dev
  composer.json
Labels: Progress: ready for review

#229 AC-939: Create unit test for Magento2\Less\AvoidIdSniff check
  Magento2/Sniffs/Less/AvoidIdSniff.php
  Magento2/Tests/Less/AbstractLessSniffUnitTestCase.php
  Magento2/Tests/Less/AvoidIdUnitTest.less
  Magento2/Tests/Less/AvoidIdUnitTest.php
  Magento2/ruleset.xml
Labels: Progress: approved

#234 Version 8 master update
  Magento2/Sniffs/Annotation/AnnotationFormatValidator.php
  Magento2/Sniffs/Annotation/MethodArgumentsSniff.php
  Magento2/Sniffs/Html/HtmlDirectiveSniff.php
  Magento2/Sniffs/Less/AvoidIdSniff.php
  Magento2/Sniffs/Namespaces/ImportsFromTestNamespaceSniff.php
  Magento2/Tests/Annotation/MethodAnnotationStructureUnitTest.inc
  Magento2/Tests/Annotation/MethodAnnotationStructureUnitTest.php
  Magento2/Tests/Annotation/MethodArgumentsUnitTest.inc
  Magento2/Tests/Annotation/MethodArgumentsUnitTest.php
  Magento2/Tests/Html/HtmlBindingUnitTest.1.inc
  Magento2/Tests/Html/HtmlDirectiveUnitTest.1.inc
  Magento2/Tests/Html/HtmlDirectiveUnitTest.2.inc
  Magento2/Tests/Html/HtmlDirectiveUnitTest.php
  Magento2/Tests/Less/AbstractLessSniffUnitTestCase.php
  Magento2/Tests/Less/AvoidIdUnitTest.less
  Magento2/Tests/Less/AvoidIdUnitTest.php
  Magento2/Tests/Namespaces/ImportsFromTestNamespaceUnitTest.inc
  Magento2/ruleset.xml
  composer.json
  composer.lock
Labels: Progress: ready for review

#233 Create phpcs static check for DiConfigTest
  Magento2/Sniffs/Legacy/DiConfigSniff.php
  Magento2/Tests/Legacy/DiConfigUnitTest.php
  Magento2/Tests/Legacy/DiConfigUnitTest.xml
  Magento2/ruleset.xml
Labels: Progress: approved

#236 AC-940: Create unit test for Magento2\Less\BracesFormattingSniff check
  Magento2/Tests/Less/BracesFormattingUnitTest.less
  Magento2/Tests/Less/BracesFormattingUnitTest.php
Labels: Progress: approved
