Repository magento/magento-coding-standard, pull requests merged in 2021-07, with the labels that each got.

#207 Run tests on Github Actions
  .github/workflows/php.yml
Labels: Progress: approved

#206 Updated webonyx/graphql-php to ^14.9
  .github/workflows/php.yml
  .travis.yml
  composer.json
  composer.lock
Labels: Partner: EY, Progress: approved, partners-contribution

#202 Avoid infinite loop when Parse Error occurs
  Magento2/Sniffs/Security/XssTemplateSniff.php
  Magento2/Tests/Security/XssTemplateUnitTest.inc
Labels: Partner: Fisheye, Progress: approved, partners-contribution

#205 Fix TypeError for phpcs->addWarning()
  Magento2/Sniffs/Exceptions/DirectThrowSniff.php
  Magento2/Sniffs/Legacy/MageEntitySniff.php
Labels: Partner: Fisheye, Progress: approved, partners-contribution

#208 Test on lowest and highest dependencies
  .github/workflows/php.yml
Labels: Progress: approved

#209 Move phpcs checks from magento2 to magento-coding-standard repo
  Magento2/Sniffs/Annotation/AnnotationFormatValidator.php
  Magento2/Sniffs/Annotation/MethodAnnotationStructureSniff.php
  Magento2/Sniffs/Annotation/MethodArgumentsSniff.php
  Magento2/Sniffs/GraphQL/ValidArgumentNameSniff.php
  Magento2/Sniffs/GraphQL/ValidEnumValueSniff.php
  Magento2/Sniffs/Html/HtmlBindingSniff.php
  Magento2/Sniffs/Html/HtmlDirectiveSniff.php
  Magento2/Sniffs/Less/AvoidIdSniff.php
  Magento2/Sniffs/Less/BracesFormattingSniff.php
  Magento2/Sniffs/Less/ClassNamingSniff.php
  Magento2/Sniffs/Less/ColonSpacingSniff.php
  Magento2/Sniffs/Less/ColourDefinitionSniff.php
  Magento2/Sniffs/Less/CombinatorIndentationSniff.php
  Magento2/Sniffs/Less/CommentLevelsSniff.php
  Magento2/Sniffs/Less/ImportantPropertySniff.php
  Magento2/Sniffs/Less/IndentationSniff.php
  Magento2/Sniffs/Less/PropertiesLineBreakSniff.php
  Magento2/Sniffs/Less/PropertiesSortingSniff.php
  Magento2/Sniffs/Less/QuotesSniff.php
  Magento2/Sniffs/Less/SelectorDelimiterSniff.php
  Magento2/Sniffs/Less/SemicolonSpacingSniff.php
  Magento2/Sniffs/Less/TokenizerSymbolsInterface.php
  Magento2/Sniffs/Less/TypeSelectorConcatenationSniff.php
  Magento2/Sniffs/Less/TypeSelectorsSniff.php
  Magento2/Sniffs/Less/VariablesSniff.php
  Magento2/Sniffs/Less/ZeroUnitsSniff.php
  Magento2/Tests/GraphQL/AbstractGraphQLSniffUnitTestCase.php
  Magento2/ruleset.xml
Labels: Progress: approved
