Repository magento/magento-coding-standard, pull requests merged in 2022-02, with the labels that each got.

#366 PHP 8.1 Compatibility
  Magento2/ruleset.xml
Labels: Progress: approved

#368 AC-2224: Remove incorrect and outdated rules
  Magento2/Sniffs/Legacy/PhtmlTemplateSniff.php
  Magento2/Sniffs/PHPCompatibility/AbstractPrivateMethodsSniff.php
  Magento2/Sniffs/PHPCompatibility/NewAttributesSniff.php
  Magento2/Sniffs/PHPCompatibility/NewInterpolatedStringDereferencingSniff.php
  Magento2/Sniffs/PHPCompatibility/NewMagicClassConstantSniff.php
  Magento2/Sniffs/PHPCompatibility/NewMagicConstantDereferencingSniff.php
  Magento2/Sniffs/PHPCompatibility/NewNestedStaticAccessSniff.php
  Magento2/Sniffs/PHPCompatibility/NewNonCapturingCatchSniff.php
  Magento2/Sniffs/PHPCompatibility/NewTrailingCommaSniff.php
  Magento2/Tests/Legacy/PhtmlTemplateUnitTest.php
  Magento2/Tests/PHPCompatibility/AbstractPrivateMethodsUnitTest.inc
  Magento2/Tests/PHPCompatibility/AbstractPrivateMethodsUnitTest.php
  Magento2/Tests/PHPCompatibility/NewAttributesUnitTest.inc
  Magento2/Tests/PHPCompatibility/NewAttributesUnitTest.php
  Magento2/Tests/PHPCompatibility/NewInterpolatedStringDereferencingUnitTest.inc
  Magento2/Tests/PHPCompatibility/NewInterpolatedStringDereferencingUnitTest.php
  Magento2/Tests/PHPCompatibility/NewMagicClassConstantUnitTest.inc
  Magento2/Tests/PHPCompatibility/NewMagicClassConstantUnitTest.php
  Magento2/Tests/PHPCompatibility/NewMagicConstantDereferencingUnitTest.inc
  Magento2/Tests/PHPCompatibility/NewMagicConstantDereferencingUnitTest.php
  Magento2/Tests/PHPCompatibility/NewNestedStaticAccessUnitTest.inc
  Magento2/Tests/PHPCompatibility/NewNestedStaticAccessUnitTest.php
  Magento2/Tests/PHPCompatibility/NewNonCapturingCatchUnitTest.inc
  Magento2/Tests/PHPCompatibility/NewNonCapturingCatchUnitTest.php
  Magento2/Tests/PHPCompatibility/NewTrailingCommaUnitTest.inc
  Magento2/Tests/PHPCompatibility/NewTrailingCommaUnitTest.php
  Magento2/ruleset.xml
Labels: Progress: approved

#367 Use development php configuration for tests
  .github/workflows/php.yml
Labels: Progress: ready for review

#369 Autofix for ThisInTemplate sniff
  Magento2/Sniffs/Templates/ThisInTemplateSniff.php
  Magento2/Tests/Templates/ThisInTemplateUnitTest.inc.fixed
  Magento2/Tests/Templates/ThisInTemplateUnitTest.php
Labels: Progress: approved

#370 Removed obsolete layout check
  Magento2/Sniffs/Legacy/LayoutSniff.php
  Magento2/Tests/Legacy/LayoutUnitTest.php
Labels: Progress: approved

#372 Improve: Exclude minified JS files.
  Magento2/ruleset.xml
Labels: partners-contribution, Progress: approved, Partner: Amasty
