Repository magento/magento-coding-standard, pull requests merged in 2023-09, with the labels that each got.

#469 Allow more recent versions of rector
  composer.json
  composer.lock
Labels: partners-contribution, Progress: ready for review, Partner: Youwe

#468 Removing dependency on symfony/polyfill, is no longer required now th…
  composer.json
  composer.lock
Labels: Progress: approved

#447 Allow readonly between phpdoc and property name
  Magento2/Sniffs/Commenting/ClassPropertyPHPDocFormattingSniff.php
  Magento2/Tests/Commenting/ClassPropertyPHPDocFormattingUnitTest.inc
Labels: Progress: approved

#358 [eslint] Enforce consistent indentation
  eslint/.eslintrc-magento
  eslint/rules/utils.js
Labels: partners-contribution, Progress: ready for review, Partner: Fisheye

#361 [eslint] Disallow useless constructs
  eslint/.eslintrc-magento
Labels: partners-contribution, Progress: ready for review, Partner: Fisheye

#364 Allow Use of Template Literals
  eslint/.eslintrc-magento
Labels: partners-contribution, Progress: approved, Partner: Fisheye

#378 Add semicolon as statement separator in the special annotation check of the `Magento2.Security.XssTemplate` sniff
  Magento2/Sniffs/Security/XssTemplateSniff.php
Labels: Progress: changes requested

#459 Update README.md
  README.md
Labels: Progress: approved

#356 [eslint] Enforce consistent spacing around keywords
  eslint/.eslintrc-magento
Labels: partners-contribution, Progress: ready for review, Partner: Fisheye
