Repository magento/magento-coding-standard, pull requests merged in 2023-03, with the labels that each got.

#426 Fix PHP error with short class names
  Magento2/Sniffs/Less/ClassNamingSniff.php
  Magento2/Tests/Less/ClassNamingUnitTest.less
Labels: partners-contribution, Progress: approved, Partner: Fisheye

#382 Add `@author` to forbidden tag list
  Magento2/Sniffs/Commenting/ClassAndInterfacePHPDocFormattingSniff.php
  Magento2/Tests/Commenting/ClassAndInterfacePHPDocFormattingUnitTest.1.inc
  Magento2/Tests/Commenting/ClassAndInterfacePHPDocFormattingUnitTest.2.inc
  Magento2/Tests/Commenting/ClassAndInterfacePHPDocFormattingUnitTest.php
Labels: partners-contribution, Progress: approved, Partner: Fisheye

#438 Auto-fix `Magento2.PHP.ShortEchoSyntax.ShortEchoTag`
  Magento2/Sniffs/PHP/ShortEchoSyntaxSniff.php
  Magento2/Tests/PHP/ShortEchoSyntaxUnitTest.inc
  Magento2/Tests/PHP/ShortEchoSyntaxUnitTest.inc.fixed
  Magento2/Tests/PHP/ShortEchoSyntaxUnitTest.php
Labels: partners-contribution, Progress: ready for review, Partner: Fisheye

#377 Resolve incorrect violation code in `Magento2.Security.XssTemplate` sniff
  Magento2/Sniffs/Security/XssTemplateSniff.php
Labels: Progress: approved
